import crypto from 'node:crypto';import type {Agent,Opportunity,Strategy,Task} from './domain';import {CoreStore} from './store';
export class OpportunityRegistry{
 constructor(private store:CoreStore){}
 async discover(){const feed=(process.env.OPPORTUNITY_FEED_URL||'').trim();if(feed){if(!feed.startsWith('https://'))throw new Error('OPPORTUNITY_FEED_URL must use HTTPS');const r=await fetch(feed,{signal:AbortSignal.timeout(10000)});if(!r.ok)throw new Error(`Opportunity feed HTTP ${r.status}`);const body:any=await r.json();for(const item of Array.isArray(body)?body:(body.opportunities||[]))this.ingestExternal(item)}return this.store.get().opportunities}
 ingestExternal(input:Partial<Opportunity>){const now=Date.now();if(!input.strategyId||!this.store.get().strategies.some(s=>s.id===input.strategyId))throw new Error('Unknown strategy');const o:Opportunity={id:input.id||crypto.randomUUID(),strategyId:input.strategyId,title:input.title||'External opportunity',source:input.source||'external-feed',discoveredAt:input.discoveredAt||now,expiresAt:input.expiresAt??null,expectedGrossSol:Number(input.expectedGrossSol||0),networkFeesSol:Number(input.networkFeesSol||0),tradingFeesSol:Number(input.tradingFeesSol||0),slippageSol:Number(input.slippageSol||0),riskCostSol:Number(input.riskCostSol||0),capitalCostSol:Number(input.capitalCostSol||0),scoreSol:0,status:'ESTIMATED',capitalRequiredSol:Number(input.capitalRequiredSol||0),evidenceUrl:input.evidenceUrl,metadata:input.metadata};return this.store.upsertOpportunity(o)}
 discoverZeroCapitalProducts(){const now=Date.now();const strategies=this.store.get().strategies;for(const p of this.store.get().revenueProducts.filter(x=>x.enabled&&Number(x.capitalRequiredSol)===0)){const strategy=strategies.find(s=>s.id===p.category)||strategies.find(s=>s.id==='analytics');if(!strategy)continue;this.store.upsertOpportunity({id:`product:${p.id}`,strategyId:strategy.id,title:`Customer revenue: ${p.name}`,source:'yabbai-product-catalog',discoveredAt:now,expiresAt:null,expectedGrossSol:0,networkFeesSol:0,tradingFeesSol:0,slippageSol:0,riskCostSol:0,capitalCostSol:0,scoreSol:0,status:'ESTIMATED',capitalRequiredSol:0,metadata:{productId:p.id,priceAmount:p.priceAmount,priceAsset:p.priceAsset,kind:'customer-revenue',note:'Potential revenue only; no customer payment has been counted.'}})}return this.store.get().opportunities.filter(o=>o.capitalRequiredSol===0)}
}
export class YieldRanker{rank(opportunities:Opportunity[]){return [...opportunities].map(o=>({...o,scoreSol:o.expectedGrossSol-o.networkFeesSol-o.tradingFeesSol-o.slippageSol-o.riskCostSol-o.capitalCostSol})).sort((a,b)=>b.scoreSol-a.scoreSol)}}
export class CurrentPredicamentEngine{state(capitalSol:number){const levels=[0,20,50,100,250,500,1000,2500,5000,10000,25000];let current=levels[0];for(const x of levels)if(capitalSol>=x)current=x;return {current,next:levels.find(x=>x>capitalSol)||null,levels,maximumReached:current}}}
export class ThresholdEngine{eligible(o:Opportunity,capitalSol:number){return o.capitalRequiredSol<=capitalSol}}
export class EarningTaskQueue{constructor(private store:CoreStore){} enqueue(o:Opportunity,agent:Agent){const idempotencyKey=`${o.id}:${agent.id}`;return this.store.addTask({id:crypto.randomUUID(),opportunityId:o.id,agentId:agent.id,stage:'discover',status:'QUEUED',idempotencyKey,createdAt:Date.now(),updatedAt:Date.now()})}}
export class FleetEngine{constructor(private store:CoreStore){} heartbeat(id:string){const s=this.store.get();const a=s.agents.find(x=>x.id===id);if(!a)throw new Error('Unknown agent');const idx=this.store.state.agents.findIndex(x=>x.id===id);this.store.state.agents[idx].heartbeat=Date.now();this.store.state.agents[idx].independentDecisionId=crypto.randomUUID();return this.store.get().agents[idx]} canEvaluate(a:Agent,o:Opportunity,strategy:Strategy){return a.status==='ACTIVE'&&a.strategyPermissions.includes(strategy.id)&&a.supportedNetworks.includes('solana')&&a.budgetSol>=o.capitalRequiredSol&&a.minimumExpectedReturnPct<=strategy.minExpectedReturnPct+1000}}
export class StrategySignalBus{constructor(private store:CoreStore){} publish(opportunityId:string,originAgentId:string,agentIds:string[]){const s={id:crypto.randomUUID(),opportunityId,createdAt:Date.now(),expiresAt:Date.now()+900000,originAgentId,sharedWith:agentIds.filter(x=>x!==originAgentId),independentRequired:true as const};return this.store.addSignal(s)}}
