import { useCallback, useEffect, useRef, useState } from 'react';
import './index.css';
import { PHANTOM_DOWNLOAD_URL, PHANTOM_MISSING_MESSAGE, getPhantomProvider, isPlausibleSolanaAddress, normalizeWalletError, resolveAddress, shortenAddress } from './wallet/phantom';
import type { PhantomProvider } from './wallet/phantom';
declare global { interface Window { solana?: PhantomProvider; phantom?: { solana?: PhantomProvider } } }
type System={system:any,verifiedRevenue:number,verifiedRevenueSol?:number,verifiedNonSolRevenue?:number,verifiedRevenueEvents:number,pendingRevenue?:number,estimatedOpportunities?:number,paidOrders?:number,fulfilledOrders?:number,executedCapital:number,observedCapitalSol:number|null,observedCapitalStatus:string,capitalSol?:number,capitalUsd?:number|null,solPriceUsd?:number|null,revenueProducts:any[],orders:any[],agents:any[],opportunities:any[],tasks:any[],transactions:any[],riskEvents:any[],audit:any[],threshold:any,treasury?:any,sweep?:any};
const money=(n:any)=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:6});const when=(n:any)=>n?new Date(n).toLocaleString():'—';
export default function App(){
const [s,setS]=useState<System|null>(null),[p,setP]=useState<any[]>([]),[b,setB]=useState<any>(null),[err,setErr]=useState(''),[busy,setBusy]=useState(false),[walletAddress,setWalletAddress]=useState(''),[walletConnecting,setWalletConnecting]=useState(false),[walletError,setWalletError]=useState(''),[walletProviderName,setWalletProviderName]=useState('Not detected'),[withdrawal,setWithdrawal]=useState<any>(null),[phantomBusy,setPhantomBusy]=useState(false),[depositAmount,setDepositAmount]=useState('0.01'),[deposit,setDeposit]=useState<any>(null);
const load=useCallback(async()=>{setErr('');const get=async(u:string)=>{const r=await fetch(u);const d=await r.json();if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d};try{const [a,ph,ba]=await Promise.all([get('/api/system/status'),get('/api/providers/health'),get('/api/wallet/balance').catch(()=>null)]);setS(a);setP(ph.providers||[]);setB(ba)}catch(e:any){setErr(e.message)}},[]);
useEffect(()=>{load();const x=setInterval(load,15000);return()=>clearInterval(x)},[load]);
// Wallet lifecycle: detect provider on mount, trusted-only silent restore (never
// opens the Phantom approval popup on page load), and live connect/disconnect/
// accountChanged events. Connecting itself never touches the server.
// Detection is reactive: late-injected providers (extension loads after the page,
// install-then-return, unlock) are picked up via window focus and after manual
// connect, so event subscriptions are never silently missing.
const subscribedProvider=useRef<PhantomProvider|null>(null);
const detachWallet=useCallback(()=>{const prev=subscribedProvider.current;subscribedProvider.current=null;if(!prev)return;const stored=(prev as unknown as {__yabbaiHandlers?:Record<'connect'|'disconnect'|'accountChanged',(arg?:unknown)=>void>}).__yabbaiHandlers;if(!stored)return;for(const ev of ['connect','disconnect','accountChanged'] as const){const h=stored[ev];if(!h)continue;try{prev.off?.(ev,h)}catch{}try{prev.removeListener?.(ev,h)}catch{}}},[]);
const subscribeWallet=useCallback((provider:PhantomProvider)=>{
  if(subscribedProvider.current===provider)return;
  detachWallet();
  const handleConnect=()=>{console.log('[Wallet] Connected');try{const address=resolveAddress(null,provider);if(address&&isPlausibleSolanaAddress(address)){setWalletAddress(address);setWalletError('')}}catch{}};
  const handleDisconnect=()=>{console.log('[Wallet] Disconnected');setWalletAddress('');setWithdrawal(null);setDeposit(null)};
  const handleAccountChanged=(next:unknown)=>{console.log('[Wallet] Account changed');try{const raw=next as {toBase58?:()=>string}|string|null|undefined;const address=typeof raw==='string'&&isPlausibleSolanaAddress(raw)?raw:resolveAddress({publicKey:raw as never},provider);if(address&&isPlausibleSolanaAddress(address)){setWalletAddress(address);setWalletError('');setWithdrawal(null);setDeposit(null);void load()}else{handleDisconnect()}}catch{handleDisconnect()}};
  (provider as unknown as {__yabbaiHandlers?:Record<string,unknown>}).__yabbaiHandlers={connect:handleConnect,disconnect:handleDisconnect,accountChanged:handleAccountChanged};
  provider.on?.('connect',handleConnect);provider.on?.('disconnect',handleDisconnect);provider.on?.('accountChanged',handleAccountChanged);
  subscribedProvider.current=provider;setWalletProviderName('Phantom');
},[detachWallet,load]);
useEffect(()=>{
  // Best-effort unsubscribe of the exact handlers on unmount.
  return()=>{const prev=subscribedProvider.current;subscribedProvider.current=null;if(!prev)return;const stored=(prev as unknown as {__yabbaiHandlers?:{connect:(arg?:unknown)=>void;disconnect:(arg?:unknown)=>void;accountChanged:(arg?:unknown)=>void}}).__yabbaiHandlers;if(!stored)return;for(const ev of ['connect','disconnect','accountChanged'] as const){const h=stored[ev];try{prev.off?.(ev,h)}catch{}try{prev.removeListener?.(ev,h)}catch{}}};
},[]);
useEffect(()=>{
  const provider=getPhantomProvider();
  setWalletProviderName(provider?'Phantom':'Not detected');
  if(!provider){console.log('[Wallet] Provider not detected');return}
  console.log('[Wallet] Provider detected');
  subscribeWallet(provider);
  let cancelled=false;
  (async()=>{
    try{
      // Silent restore only: approved dapps reconnect without a popup.
      const response=await provider.connect({onlyIfTrusted:true});
      const address=resolveAddress(response,provider);
      if(!cancelled&&address&&isPlausibleSolanaAddress(address)){console.log('[Wallet] Session restored');setWalletAddress(address);setWalletError('')}
    }catch{/* not previously approved: stay disconnected, no popup, no error */}
  })();
  // Late providers (installed/unlocked/injected after mount) are picked up when
  // the tab regains focus. Popup-free: never calls connect() here.
  const handleFocus=()=>{try{const late=getPhantomProvider();if(!late)return;if(subscribedProvider.current!==late){console.log('[Wallet] Provider detected on focus');subscribeWallet(late)}const current=resolveAddress(null,late);if(current&&isPlausibleSolanaAddress(current))setWalletAddress((prev)=>prev||current)}catch{}};
  window.addEventListener('focus',handleFocus);
  return()=>{cancelled=true;window.removeEventListener('focus',handleFocus)};
},[load,subscribeWallet]);
const connectPhantom=async()=>{console.log('[Wallet] Connect clicked');const provider=getPhantomProvider();setWalletProviderName(provider?'Phantom':'Not detected');if(!provider){console.log('[Wallet] Provider not detected');setWalletError(PHANTOM_MISSING_MESSAGE);return}console.log('[Wallet] Provider detected');console.log('[Wallet] Connecting');setWalletConnecting(true);setWalletError('');try{const response=await provider.connect();const address=resolveAddress(response,provider);if(!address||!isPlausibleSolanaAddress(address))throw Error('Phantom connected, but no public key was returned.');console.log('[Wallet] Connected');setWalletAddress(address);subscribeWallet(provider);await load()}catch(e:unknown){console.log('[Wallet] Connection failed');setWalletError(normalizeWalletError(e))}finally{setWalletConnecting(false)}};
const disconnectPhantom=async()=>{console.log('[Wallet] Disconnect clicked');const provider=getPhantomProvider();try{await provider?.disconnect?.()}catch{/* provider may not support disconnect; local state is still cleared */}console.log('[Wallet] Disconnected');setWalletAddress('');setWithdrawal(null);setDeposit(null);setWalletError('')};
const preflightWithdrawal=async()=>{setPhantomBusy(true);setWithdrawal(null);setErr('');try{if(!walletAddress)throw Error('Connect Phantom first');const r=await fetch('/api/treasury/phantom/initial-withdrawal/prepare',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({phantomWallet:walletAddress})});const d=await r.json();if(!r.ok)throw Error(d.error||'Withdrawal preflight blocked');setWithdrawal(d)}catch(e:any){setErr(e.message)}finally{setPhantomBusy(false)}};
const prepareDeposit=async()=>{setPhantomBusy(true);setDeposit(null);setErr('');try{if(!walletAddress)throw Error('Connect Phantom first');const r=await fetch('/api/treasury/phantom/deposit/prepare',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({phantomWallet:walletAddress,amountSol:depositAmount})});const d=await r.json();if(!r.ok)throw Error(d.error||'Deposit preflight blocked');setDeposit(d)}catch(e:any){setErr(e.message)}finally{setPhantomBusy(false)}};
const executeDeposit=async()=>{const provider=getPhantomProvider();if(!deposit?.serializedTransaction||!provider?.signAndSendTransaction)throw Error('Phantom transaction signing is unavailable');setPhantomBusy(true);setErr('');try{const raw=Uint8Array.from(atob(deposit.serializedTransaction),c=>c.charCodeAt(0));const tx=await import('@solana/web3.js').then(m=>m.Transaction.from(raw));const sent=await provider.signAndSendTransaction(tx);setDeposit({...deposit,signature:sent.signature,status:'SUBMITTED'});await load()}catch(e:any){setErr(e.message)}finally{setPhantomBusy(false)}};
const action=async(u:string,body:any={})=>{setBusy(true);try{const r=await fetch(u,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);await load()}catch(e:any){setErr(e.message)}finally{setBusy(false)}};
const productStats=(pid:string)=>{const orders=(s?.orders||[]).filter((o:any)=>o.productId===pid);return {orders:orders.length,paid:orders.filter((o:any)=>o.status==='PAID'||o.status==='FULFILLED').length,fulfilled:orders.filter((o:any)=>o.status==='FULFILLED').length};};
const reserved=Number((s as any)?.treasury?.minReserveSol ?? 0.05);
const observed=Number(s?.observedCapitalSol ?? b?.sol ?? 0);
const available=s?.observedCapitalSol!=null?Math.max(0,Number(s.observedCapitalSol)-reserved):null;
return <div className="shell"><header><div><h1>YABBAI Command Center</h1><p>Evidence-first revenue, treasury and agent operations</p></div><div className="actions"><span className="pill">{s?.system?.emergencyStop?'EMERGENCY STOP':'AUTOPILOT ARMED'}</span><button onClick={load}>Refresh</button></div></header>{err&&<div className="error">{err}</div>}<main>
<section className="grid top"><Card title="Verified revenue"><div className="big">{money(s?.verifiedRevenue)} SOL</div><small>Only verified evidence enters this figure. Estimated opportunities are never counted here.</small><small>{s?.verifiedRevenueEvents||0} verified events · {s?.pendingRevenue||0} pending · {s?.estimatedOpportunities||0} estimated opportunities</small></Card><Card title="Available observed capital"><div className="big">{money(b?.sol ?? s?.observedCapitalSol)} SOL</div><small>{b?.address||(s as any)?.treasury?.watchWallet||'No WATCH_WALLET configured'}</small><small>Source: {b?.rpcProvider||'—'} · {b?.status||s?.observedCapitalStatus||'UNKNOWN'} · Network: {(s as any)?.treasury?.network||'—'}</small></Card><Card title="Capability threshold"><div className="big">${money(s?.threshold?.current||0)}</div><small>Next capability state: {s?.threshold?.next?`$${money(s.threshold.next)}`:'10K+'}</small><small>Verified capital: {money(s?.capitalSol)} SOL{s?.capitalUsd!=null?` ≈ $${money(s.capitalUsd)}`:''} {s?.solPriceUsd?`(SOL $${money(s.solPriceUsd)})`:'(price UNKNOWN)'}</small></Card></section>
<section className="grid"><Card title="Treasury"><div className="big">{s?.observedCapitalStatus==='VERIFIED'?money(s?.observedCapitalSol):money(b?.sol)??'Unavailable'} SOL</div><small>Observed wallet balance (live RPC, VERIFIED) vs executed allocations {money(s?.executedCapital)} SOL.</small><table><tbody><tr><td>Verified SOL balance</td><td className="mono">{money(s?.verifiedRevenue)} SOL</td></tr><tr><td>Observed wallet balance</td><td className="mono">{s?.observedCapitalStatus==='VERIFIED'?money(s?.observedCapitalSol):'UNKNOWN'} SOL</td></tr><tr><td>Reserved SOL</td><td className="mono">{money(reserved)} SOL</td></tr><tr><td>Available SOL</td><td className="mono">{available!=null?money(available):'UNKNOWN'}</td></tr><tr><td>Minimum reserve</td><td className="mono">{money(reserved)} SOL</td></tr><tr><td>Treasury destination</td><td className="mono">{(s as any)?.treasury?.destination||b?.address||'—'}</td></tr><tr><td>Network</td><td>{(s as any)?.treasury?.network||'—'}</td></tr></tbody></table></Card><Card title="Real revenue engine"><div className="big">{money(s?.verifiedRevenue)} SOL</div><small>{s?.verifiedRevenueEvents||0} verified SOL revenue events. This figure changes only after authoritative payment evidence.</small><small>Pending: {s?.pendingRevenue||0} · Estimated opportunities: {s?.estimatedOpportunities||0} · Paid orders: {s?.paidOrders||0} · Fulfilled: {s?.fulfilledOrders||0}</small><div className="tierbar">{(s?.threshold?.levels||[]).map((x:number)=><span key={x} className={x===(s?.threshold?.current||0)?'tier current':'tier'}>${x>=1000?`${x/1000}K`:x}</span>)}</div><p>Current capability: <b>${s?.threshold?.current||0}</b> · Next: <b>{s?.threshold?.next?`$${s.threshold.next}`:'MAXIMUM'}</b> · Maximum reached: <b>${s?.threshold?.maximumReached||0}</b></p><small>Current verified capital: {money(s?.capitalSol)} SOL · Tier is a capability state, not a profit guarantee.</small></Card></section>
<section className="grid"><Card title="Phantom wallet">
<div className="row"><span className="mono" title={walletAddress||undefined}>{walletAddress?shortenAddress(walletAddress):'Not connected'}</span>{!walletAddress&&<button disabled={walletConnecting} onClick={connectPhantom}>{walletConnecting?'Connecting…':'Connect Phantom'}</button>}{walletAddress&&<><button disabled={walletConnecting} onClick={connectPhantom}>{walletConnecting?'Connecting…':shortenAddress(walletAddress)}</button><button disabled={walletConnecting} onClick={disconnectPhantom}>Disconnect</button></>}</div>
<div className="wallet-status"><span>Wallet</span><span>Provider: {walletProviderName}</span><span>Status: {walletConnecting?'Connecting…':walletAddress?'Connected':'Disconnected'}</span><span>Address: {walletAddress?shortenAddress(walletAddress):'—'}</span></div>
{walletError&&<div className="error" role="alert">{walletError}{walletProviderName==='Not detected'&&<span> Get Phantom at <a href={PHANTOM_DOWNLOAD_URL} target="_blank" rel="noreferrer">phantom.com/download</a>, install it, reload this page, then connect.</span>}</div>}
<p>Phantom is used as the recipient and fee payer. YABBAI never receives or stores the wallet private key.</p>
<div className="actions"><button disabled={!walletAddress||phantomBusy} onClick={preflightWithdrawal}>Preflight 30% initial withdrawal</button></div>
{withdrawal&&<div className="notice"><b>SIMULATION PASSED</b><br/>30% withdrawal: {money(withdrawal.amountSol)} SOL<br/>Network fee: {money(withdrawal.feeSol)} SOL<br/><small>Phantom has not been charged. Source authorization is still required before execution.</small></div>}
<div className="row"><input value={depositAmount} onChange={e=>setDepositAmount(e.target.value)} inputMode="decimal" aria-label="Deposit amount in SOL" /><button disabled={!walletAddress||phantomBusy} onClick={prepareDeposit}>Prepare treasury deposit</button>{deposit?.serializedTransaction&&<button disabled={phantomBusy} onClick={executeDeposit}>Sign & Send</button>}</div>
{deposit&&<small>Deposit preflight: {deposit.status||'SIMULATION_PASSED'} · fee {money(deposit.feeSol)} SOL{deposit.signature?` · ${deposit.signature}`:''}</small>}
</Card><Card title="Receive funds"><p>Send supported funds to the configured treasury/vault address below. This address is read from the server configuration.</p><div className="mono">{b?.address||(s as any)?.treasury?.destination||'TREASURY_VAULT_ADDRESS not configured'}</div><small>Never send funds until you have independently verified the displayed address.</small><p style={{marginTop:12}}>Sweep policy: {(s as any)?.sweep?.percent ?? 10}% · every {(s as any)?.sweep?.intervalMinutes ?? 5} min · max {(s as any)?.sweep?.maxDaily ?? 50}/day · reserve {money(reserved)} SOL · basis: verified revenue only.</p></Card></section>
<section><Card title="Revenue products"><p>Legitimate service products. A product is not counted as revenue until a real customer payment is verified. Estimated ≠ realized.</p><table><thead><tr><th>Product</th><th>Price</th><th>Orders</th><th>Paid</th><th>Fulfilled</th><th>Revenue basis</th></tr></thead><tbody>{(s?.revenueProducts||[]).map((x:any)=>{const st=productStats(x.id);return <tr key={x.id}><td><b>{x.name}</b><br/><small>{x.description}</small></td><td className="mono">{x.priceAmount} {x.priceAsset}</td><td>{st.orders}</td><td>{st.paid}</td><td>{st.fulfilled}</td><td><span className="badge">VERIFIED ONLY</span></td></tr>})}</tbody></table></Card></section>
<section className="grid"><Card title="Capital state"><div className="big">{s?.observedCapitalStatus==='VERIFIED'?money(s?.observedCapitalSol):'Unavailable'} SOL</div><small>Observed treasury/watched-wallet balance from live RPC.</small><p>Executed allocations are tracked separately: {money(s?.executedCapital)} SOL.</p><p>Reserve enforced: {money(reserved)} SOL · Available: {available!=null?money(available)+' SOL':'UNKNOWN'}</p></Card><Card title="Verified orders"><table><thead><tr><th>Product</th><th>Amount</th><th>Status</th></tr></thead><tbody>{(s?.orders||[]).slice(0,10).map((o:any)=><tr key={o.id}><td>{o.productId}</td><td>{o.amount} {o.asset}</td><td>{o.status}</td></tr>)}</tbody></table></Card></section>
<section className="grid"><Card title="Autopilot"><p>Discover → validate → rank → queue → verify → account. Capital execution remains authorization-gated.</p><div className="actions"><button disabled={busy} onClick={()=>action('/api/opportunities/discover')}>Discover</button><button disabled={busy} onClick={()=>action('/api/autopilot/tick')}>Run tick</button><button disabled={busy} onClick={()=>action('/api/security/stop',{reason:'Operator stop'})}>Emergency stop</button><button disabled={busy} onClick={()=>action('/api/security/start')}>Release stop</button></div><small>Emergency stop persists across restarts. When active, no autonomous execution, treasury transfers, allocations or swaps run. Read-only monitoring continues.</small></Card><Card title="Provider health"><table><thead><tr><th>Provider</th><th>State</th><th>Latency</th><th>Error rate</th></tr></thead><tbody>{p.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.isHealthy?'HEALTHY':'UNKNOWN'}{x.isActive?' · ACTIVE':''}</td><td>{x.latencyMs??'—'}{x.latencyMs?' ms':''}</td><td>{x.errorRatePercent??'—'}%</td></tr>)}</tbody></table></Card></section>
<section><Card title="20-agent fleet"><p>Each agent evaluates independently with its own decision id. Signals may be shared, but no agent blindly copies another.</p><table><thead><tr><th>Agent</th><th>Wallet</th><th>Status</th><th>Budget</th><th>Strategy</th><th>Risk</th><th>Heartbeat</th><th>Last decision</th><th>Verified revenue</th></tr></thead><tbody>{(s?.agents||[]).map((a:any)=><tr key={a.id}><td>{a.id}</td><td className="mono">{a.walletAddress||'UNCONFIGURED'}</td><td>{a.status}</td><td>{money(a.budgetSol)} SOL</td><td>{(a.strategyPermissions||[]).slice(0,3).join(', ')}{(a.strategyPermissions||[]).length>3?'…':''}</td><td>{a.riskProfile||'—'}</td><td>{when(a.heartbeat)}</td><td className="mono">{a.independentDecisionId?a.independentDecisionId.slice(0,8)+'…':'—'}</td><td>{money(a.performance?.verifiedRevenueSol)} SOL</td></tr>)}</tbody></table></Card></section>
<section><Card title="Opportunity ranking"><table><thead><tr><th>Opportunity</th><th>Strategy</th><th>Expected</th><th>Costs</th><th>Score</th><th>Status</th></tr></thead><tbody>{(s?.opportunities||[]).slice(0,30).map((o:any)=><tr key={o.id}><td>{o.title}</td><td>{o.strategyId}</td><td>{money(o.expectedGrossSol)}</td><td>{money(Number(o.networkFeesSol)+Number(o.tradingFeesSol)+Number(o.slippageSol)+Number(o.riskCostSol)+Number(o.capitalCostSol))}</td><td>{money(o.scoreSol)}</td><td><span className="badge">{o.status}</span></td></tr>)}</tbody></table></Card></section>
<section className="grid"><Card title="Earning task queue"><table><thead><tr><th>Task</th><th>Agent</th><th>Stage</th><th>Status</th></tr></thead><tbody>{(s?.tasks||[]).slice(0,30).map((t:any)=><tr key={t.id}><td>{t.id.slice(0,8)}…</td><td>{t.agentId}</td><td>{t.stage}</td><td>{t.status}</td></tr>)}</tbody></table></Card><Card title="Transaction lifecycle"><table><thead><tr><th>Signature</th><th>State</th><th>Amount</th><th>Destination</th><th>Created</th><th>Verification</th></tr></thead><tbody>{(s?.transactions||[]).slice(0,20).map((t:any)=><tr key={t.id}><td className="mono">{t.signature?t.signature.slice(0,12)+'…':t.id.slice(0,8)+'…'}</td><td>{t.state}</td><td>{t.amountSol||'—'}</td><td className="mono">{t.destination?t.destination.slice(0,12)+'…':'—'}</td><td>{when(t.createdAt)}</td><td>{t.state==='CONFIRMED'||t.state==='VERIFIED'?'VERIFIED':t.state==='RECONCILIATION_REQUIRED'?'REVIEW':t.state==='FAILED'?'FAILED':'UNKNOWN'}</td></tr>)}</tbody></table></Card></section>
<section className="grid"><Card title="Risk"><table><thead><tr><th>Time</th><th>Type</th><th>Severity</th><th>Message</th></tr></thead><tbody>{(s?.riskEvents||[]).slice(0,20).map((r:any)=><tr key={r.id}><td>{when(r.createdAt)}</td><td>{r.type}</td><td>{r.severity}</td><td>{r.message}</td></tr>)}</tbody></table><small>Provider failures, blocked transactions, policy violations, unknown transactions and reconciliation-required states appear here. Emergency stop: {s?.system?.emergencyStop?'ENGAGED ('+(s?.system?.reason||'no reason')+')':'released'}.</small></Card><Card title="Audit"><table><thead><tr><th>Time</th><th>Action</th><th>Entity</th><th>Result</th></tr></thead><tbody>{(s?.audit||[]).slice(0,20).map((a:any)=><tr key={a.id}><td>{when(a.at)}</td><td>{a.action}</td><td className="mono">{a.entityType}:{String(a.entityId).slice(0,10)}…</td><td>{a.result}</td></tr>)}</tbody></table></Card></section>
<section className="notice"><b>Real-earning model:</b> YABBAI starts with zero-capital service opportunities, records customer payments only after authoritative verification, and progressively unlocks capability tiers from verified capital. No tier implies guaranteed profit. <br/><br/><b>Production safety model:</b> YABBAI does not store treasury private keys, invent profit, or silently sign transfers. Revenue is separate from estimates; unknown transaction states require reconciliation; capital movement requires explicit user/multisig authorization. Legitimate zero-capital services can be discovered and queued, but the platform cannot manufacture customers or guarantee earnings.</section>
</main></div>}
function Card({title,children}:{title:string,children:any}){return <div className="card"><h2>{title}</h2>{children}</div>}
