create extension if not exists pgcrypto;
create table if not exists agents(id text primary key,wallet_address text,strategy_permissions jsonb not null default '[]',budget_sol numeric not null default 0,risk_profile text not null,supported_networks jsonb not null default '["solana"]',minimum_expected_return_pct numeric not null default 0,gas_reserve_sol numeric not null default 0,daily_loss_limit_sol numeric not null default 0,exposure_limit_sol numeric not null default 0,performance jsonb not null default '{}',status text not null,heartbeat bigint not null,independent_decision_id uuid);
create table if not exists strategies(id text primary key,name text not null,category text not null,capital_required_sol numeric not null default 0,min_expected_return_pct numeric not null default 0,risk_level text not null,supports_zero_capital boolean not null default false,enabled boolean not null default true,description text not null);
create table if not exists opportunities(id uuid primary key,strategy_id text not null references strategies(id),title text not null,source text not null,discovered_at bigint not null,expires_at bigint,expected_gross_sol numeric not null default 0,network_fees_sol numeric not null default 0,trading_fees_sol numeric not null default 0,slippage_sol numeric not null default 0,risk_cost_sol numeric not null default 0,capital_cost_sol numeric not null default 0,score_sol numeric not null default 0,status text not null,capital_required_sol numeric not null default 0,evidence_url text,metadata jsonb);
create table if not exists signals(id uuid primary key,opportunity_id uuid not null,created_at bigint not null,expires_at bigint,origin_agent_id text not null,shared_with jsonb not null default '[]',independent_required boolean not null default true);
create table if not exists tasks(id uuid primary key,opportunity_id uuid not null,agent_id text not null,stage text not null,status text not null,idempotency_key text unique not null,created_at bigint not null,updated_at bigint not null,reason text);
create table if not exists allocations(id uuid primary key,bucket text not null,amount_sol numeric not null,agent_id text,strategy_id text,status text not null,created_at bigint not null);
create table if not exists revenue(id uuid primary key,source text not null,external_id text not null,recipient text,asset text not null,amount numeric not null,network text not null,timestamp bigint not null,signature text,status text not null,idempotency_key text unique not null,evidence text not null,created_at bigint not null);
create table if not exists transactions(id uuid primary key,kind text not null,state text not null,signature text,created_at bigint not null,updated_at bigint not null,idempotency_key text unique not null,amount_sol numeric,destination text,error text);
create table if not exists risk_events(id uuid primary key,type text not null,severity text not null,message text not null,created_at bigint not null,entity_id text);
create table if not exists audit_logs(id uuid primary key,at bigint not null,action text not null,actor text not null,entity_type text not null,entity_id text not null,result text not null,metadata jsonb);
create index if not exists opportunities_score_idx on opportunities(score_sol desc);create index if not exists revenue_status_idx on revenue(status);create index if not exists transactions_state_idx on transactions(state);

do $$ declare t text; begin foreach t in array array['agents','strategies','opportunities','signals','tasks','allocations','revenue','transactions','risk_events','audit_logs'] loop execute format('alter table %I enable row level security',t); if not exists(select 1 from pg_policies where tablename=t and policyname=t||'_select') then execute format('create policy %I on %I for select to authenticated using (true)',t||'_select',t); end if; if not exists(select 1 from pg_policies where tablename=t and policyname=t||'_insert') then execute format('create policy %I on %I for insert to authenticated with check (true)',t||'_insert',t); end if; if not exists(select 1 from pg_policies where tablename=t and policyname=t||'_update') then execute format('create policy %I on %I for update to authenticated using (true) with check (true)',t||'_update',t); end if; end loop; end $$;

create table if not exists revenue_products(id text primary key,name text not null,category text not null,description text not null,price_amount numeric not null,price_asset text not null,delivery_mode text not null,capital_required_sol numeric not null default 0,enabled boolean not null default true,created_at bigint not null);
create table if not exists revenue_orders(id uuid primary key,product_id text not null references revenue_products(id),customer_ref text not null,amount numeric not null,asset text not null,network text not null,status text not null,payment_revenue_id uuid,created_at bigint not null,updated_at bigint not null);
alter table revenue_products enable row level security; alter table revenue_orders enable row level security;
